name: Run Vitest & Playwright E2E

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # Run Vitest (Unit + Integration)
      - name: Run Vitest
        run: npm run test

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Start Vite dev server in background & wait for it
      - name: Start and wait for app
        run: |
          npm run dev &
          npx wait-on http://localhost:5173

      # Run Playwright E2E tests
      - name: Run E2E tests
        run: npm run test:e2e
